default_install_hook_types: [pre-commit]
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6" # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.2
          - "@prettier/plugin-xml@0.12.0"
        exclude: "{{cookiecutter.repo_name}}/.obsidian/"
