default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=no"]
      - id: pretty-format-json
  - repo: https://github.com/google/yamlfmt
    rev: v0.13.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.1
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
        name: commitizen check
        description: >
          Check whether the current commit message follows committing rules. Allow empty commit messages by default, because they typically indicate to Git that the commit should be aborted.

        entry: cz check
        args: [--allow-abort, --commit-msg-file]
        stages: [commit-msg]
        language: python
        language_version: python3
        minimum_pre_commit_version: "1.4.3"
