name: build_page
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv.
          version: "0.4.20"
      - name: Set up Python
        run: uv python install 3.12
      - run: uv pip install -r requirements.txt
      - run: mkdocs gh-deploy --force --config-file mkdocs.yaml
